services:
  kafka:
    image: apache/kafka:4.3.0
    container_name: kafka
    ports:
      - "29092:29092" # host_port:container_port
    environment:
      # Identity
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # Listeners
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Clusters
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      # Nodes
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Instant assignment to consumer group partitions
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1.0"

  kafka-init:
    image: apache/kafka:4.3.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 \
          --create --if-not-exists \
          --topic transactions \
          --partitions 3 \
          --replication-factor 1
        echo 'Topic "transactions" is ready:'
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 \
          --describe --topic transactions

  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: streaming_rag
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: pg_isready -U rag -d streaming_rag
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "0.5"

  pgweb:
    image: sosedoff/pgweb:latest
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://rag:${POSTGRES_PASSWORD}@postgres:5432/streaming_rag?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.25"

volumes:
  kafka-data:
  postgres-data:
